# Hybrid Models for Recommendation Systems

Load Pandas, we are going to need it for manipulating data

In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

Now load the data

In [16]:
user_ratings_df = pd.read_csv("user_ratings.csv")
user_features_df = pd.read_csv("user_features.csv")
item_features_df = pd.read_csv("item_features.csv")
user_ratings_df

The Call of Cthulhu   Frankenstein   Dracula   Neuromancer   Space Odyssey
0                  8.0            2.0       NaN           5.0             4.0
1                  3.0            2.0       NaN           7.0             7.0
2                  9.0            NaN       7.0           8.0             5.0
3                  NaN            NaN       7.0           8.0             9.0
4                  NaN            1.0       8.0           3.0             7.0
5                  2.0            3.0       5.0           NaN             NaN
6                  4.0            2.0       NaN           2.0             7.0
7                  7.0            1.0       2.0           7.0             9.0
8                  3.0            3.0       NaN           7.0             3.0
9                  4.0            NaN       5.0           3.0             3.0

In [17]:
user_features_df

Sex   Over60
0  1.0      0.0
1  0.0      1.0
2  0.0      0.0
3  1.0      0.0
4  0.0      1.0
5  0.0      0.0
6  0.0      0.0
7  1.0      0.0
8  0.0      1.0
9  1.0      0.0

In [18]:
item_features_df

Critic0   Critic1
0      0.3       0.9
1      0.9       0.3
2      0.6       0.4
3      0.2       0.1
4      0.7       0.8

In [22]:
user_ratings_df = pd.read_csv("user_ratings.csv")
user_features_df = pd.read_csv("user_features.csv")
item_features_df = pd.read_csv("item_features.csv")


user_features_df["key"] = 0
user_features_df["user_id"] = range(0,user_features_df.shape[0])
item_features_df["key"] = 0
item_features_df["item_id"] = range(0,item_features_df.shape[0])

merged_df = pd.merge(user_features_df, item_features_df,left_index=True,on="key")
merged_df["rating"] = list(map(lambda ids: user_ratings_df.values[ids[1]][ids[2]], 
                          merged_df[["user_id", "item_id"]].itertuples()))
merged_df






Sex   Over60  key  user_id  Critic0   Critic1  item_id  rating
0  1.0      0.0    0        0      0.3       0.9        0     8.0
1  1.0      0.0    0        0      0.9       0.3        1     2.0
2  1.0      0.0    0        0      0.6       0.4        2     NaN
3  1.0      0.0    0        0      0.2       0.1        3     5.0
4  1.0      0.0    0        0      0.7       0.8        4     4.0
0  0.0      1.0    0        1      0.3       0.9        0     3.0
1  0.0      1.0    0        1      0.9       0.3        1     2.0
2  0.0      1.0    0        1      0.6       0.4        2     NaN
3  0.0      1.0    0        1      0.2       0.1        3     7.0
4  0.0      1.0    0        1      0.7       0.8        4     7.0
0  0.0      0.0    0        2      0.3       0.9        0     9.0
1  0.0      0.0    0        2      0.9       0.3        1     NaN
2  0.0      0.0    0        2      0.6       0.4        2     7.0
3  0.0      0.0    0        2      0.2       0.1        3     8.0
4  0.0      0.0    0        2      0.7       0.8        4     5.0
0  1.0      0.0    0        3      0.3       0.9        0     NaN
1  1.0      0.0    0        3      0.9       0.3        1     NaN
2  1.0      0.0    0        3      0.6       0.4        2     7.0
3  1.0      0.0    0        3      0.2       0.1        3     8.0
4  1.0      0.0    0        3      0.7       0.8        4     9.0
0  0.0      1.0    0        4      0.3       0.9        0     NaN
1  0.0      1.0    0        4      0.9       0.3        1     1.0
2  0.0      1.0    0        4      0.6       0.4        2     8.0
3  0.0      1.0    0        4      0.2       0.1        3     3.0
4  0.0      1.0    0        4      0.7       0.8        4     7.0
0  0.0      0.0    0        5      0.3       0.9        0     2.0
1  0.0      0.0    0        5      0.9       0.3        1     3.0
2  0.0      0.0    0        5      0.6       0.4        2     5.0
3  0.0      0.0    0        5      0.2       0.1        3     NaN
4  0.0      0.0    0        5      0.7       0.8        4     NaN
0  0.0      0.0    0        6      0.3       0.9        0     4.0
1  0.0      0.0    0        6      0.9       0.3        1     2.0
2  0.0      0.0    0        6      0.6       0.4        2     NaN
3  0.0      0.0    0        6      0.2       0.1        3     2.0
4  0.0      0.0    0        6      0.7       0.8        4     7.0
0  1.0      0.0    0        7      0.3       0.9        0     7.0
1  1.0      0.0    0        7      0.9       0.3        1     1.0
2  1.0      0.0    0        7      0.6       0.4        2     2.0
3  1.0      0.0    0        7      0.2       0.1        3     7.0
4  1.0      0.0    0        7      0.7       0.8        4     9.0
0  0.0      1.0    0        8      0.3       0.9        0     3.0
1  0.0      1.0    0        8      0.9       0.3        1     3.0
2  0.0      1.0    0        8      0.6       0.4        2     NaN
3  0.0      1.0    0        8      0.2       0.1        3     7.0
4  0.0      1.0    0        8      0.7       0.8        4     3.0
0  1.0      0.0    0        9      0.3       0.9        0     4.0
1  1.0      0.0    0        9      0.9       0.3        1     NaN
2  1.0      0.0    0        9      0.6       0.4        2     5.0
3  1.0      0.0    0        9      0.2       0.1        3     3.0
4  1.0      0.0    0        9      0.7       0.8        4     3.0

In [24]:

train = merged_df.dropna()

test = merged_df[merged_df.isnull().any(axis=1)]
test
print (test.to_latex())



\begin{tabular}{lrrrrrrrr}
\toprule
{} &  Sex &   Over60 &  key &  user\_id &  Critic0 &   Critic1 &  item\_id &  rating \\
\midrule
2 &  1.0 &      0.0 &    0 &        0 &      0.6 &       0.4 &        2 &     NaN \\
2 &  0.0 &      1.0 &    0 &        1 &      0.6 &       0.4 &        2 &     NaN \\
1 &  0.0 &      0.0 &    0 &        2 &      0.9 &       0.3 &        1 &     NaN \\
0 &  1.0 &      0.0 &    0 &        3 &      0.3 &       0.9 &        0 &     NaN \\
1 &  1.0 &      0.0 &    0 &        3 &      0.9 &       0.3 &        1 &     NaN \\
0 &  0.0 &      1.0 &    0 &        4 &      0.3 &       0.9 &        0 &     NaN \\
3 &  0.0 &      0.0 &    0 &        5 &      0.2 &       0.1 &        3 &     NaN \\
4 &  0.0 &      0.0 &    0 &        5 &      0.7 &       0.8 &        4 &     NaN \\
2 &  0.0 &      0.0 &    0 &        6 &      0.6 &       0.4 &        2 &     NaN \\
2 &  0.0 &      1.0 &    0 &        8 &      0.6 &       0.4 &        2 &     NaN \\
1 &  1.0 &      0

In [43]:
n_latent_features = 2

user_ratings = user_ratings_df.values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_latent_features))
user_features = user_features_df.values
item_features = item_features_df.values

print (item_features_df.to_latex())


\begin{tabular}{lrrrr}
\toprule
{} &  Critic0 &   Critic1 &  key &  item\_id \\
\midrule
0 &      0.3 &       0.9 &    0 &        0 \\
1 &      0.9 &       0.3 &    0 &        1 \\
2 &      0.6 &       0.4 &    0 &        2 \\
3 &      0.2 &       0.1 &    0 &        3 \\
4 &      0.7 &       0.8 &    0 &        4 \\
\bottomrule
\end{tabular}



In [48]:
user_features = np.concatenate([np.ones(shape = (user_features.shape[0],1)), user_features], axis = 1)
item_features = np.concatenate([np.ones(shape = (item_features.shape[0],1)), item_features], axis = 1)

In [52]:
user_features_weights = np.random.random((user_ratings.shape[0], user_features.shape[1] ))
item_features_weights = np.random.random((user_ratings.shape[1],item_features.shape[1] ))

user_features.shape

# print user_features

(10, 5)

In [55]:
print(user_features)
user_features_weights.shape

[[1. 1. 0. 0. 0.]
 [1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 2.]
 [1. 1. 0. 0. 3.]
 [1. 0. 1. 0. 4.]
 [1. 0. 0. 0. 5.]
 [1. 0. 0. 0. 6.]
 [1. 1. 0. 0. 7.]
 [1. 0. 1. 0. 8.]
 [1. 1. 0. 0. 9.]]


(10, 5)

In [57]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    
    user_score = user_features_weights[user_id].dot(user_features[user_id])
    item_score = item_features_weights[item_id].dot(item_features[item_id])
    #print user_preference.dot(item_preference), user_score, item_score
    return user_preference.dot(item_preference) + user_score + item_score

def train(user_id, item_id, rating,alpha = 0.001, 
                                   latent_feature_weight_decay = 0.1, 
                                   user_weight_decay = 0.01,
                                   item_weight_decay = 0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  ( prediction_rating - rating );
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err *  ( latent_item_features[item_id] + latent_feature_weight_decay*latent_user_preferences[user_id])
    latent_item_features[item_id] -= alpha * err * ( user_pref_values + latent_feature_weight_decay*latent_item_features[item_id])
    
    user_features_weights[user_id] -=alpha * err *(  user_features[user_id] + user_weight_decay* user_features_weights[user_id])
    item_features_weights[item_id] -=alpha * err * ( item_features_weights[item_id] + item_weight_decay* item_features_weights[item_id])
    
    
    return err
    


def sgd(iterations = 30000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(0,iterations):
        error = []
        for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if(not np.isnan(rating)):
                    err = train(user_id,item_id,rating)
                    error.append(err)
    mse = (np.array(error) ** 2).mean()          
    print (mse)
                    
                    
    
                    
                    
    


In [58]:
for _ in range(0,10): 
    sgd()

0.2786867130910874
0.274845661122189
0.27373887434866084
0.2732778916382687
0.27306969346642407
0.2729884942361094
0.27298266750823896
0.27302782626438005
0.2731115223605411
0.2732272533819322


In [ ]:
predictions = np.zeros(shape = (latent_user_preferences.shape[0], latent_item_features.shape[0]) )
#print latent_user_preferences
print user_features_weights
print item_features_weights
for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                predictions[user_id,item_id] =  predict_rating(user_id,item_id)

  

In [ ]:
values = [zip(user_ratings[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns
comparison_data.applymap(lambda (x,y): "(%2.3f|%2.3f)"%(x,y))

In [ ]:
comparison_data

In [ ]:
d = comparison_data.to_latex()
text_file = open("comparison.txt", "w")
text_file.write(d)
text_file.close()